import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/GamePlan.module.css'
import Nav from '@/components/NavBar'

export default function Home() {
  return (
    <>
     <Head>
        <title>LightSpeed
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>
        
      </main>
    </>

  )
}