import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Nav from '@/components/NavBar'
import VideoPromo from '@/components/PromoVideo'
import FooterBar from '@/components/Footer'
import Carousel from '@/components/Carousel'
import AlienCar from '@/components/AlienCaro'

export default function Home() {
  return (
    <>
      <Head>
        <title>LightSpeed
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className={styles.main}>
      <Nav/>
      <div id="home">
    <VideoPromo/>
      </div>
      <div id="playnow" className={styles.attention}>
        <h3 className={styles.fast}>For the Fastest Astronaut</h3>
      <h1 className={styles.header}>Light Speed</h1>
      <button className={styles.playbtn}>Play Now</button>
        </div>
        <div className={styles.beware}>
        <div className={styles.des}>
          <h1 className={styles.warning}>BEWARE OF THE BLACKHOLE</h1>
          <p>As you gear up to travel across the solar system in an all out spacecraft race, beware of the many challenges ahead of you. Watch out for meteorites and aliens, hold on to your map, keep your memory sharp, and keep track of your fuel! Take the lead and be the first one back to the Sun and most importantly... don't be swept up by the blackhole.</p>
          <p>Ready.. Set.. Go!</p>
          </div>
          <Image className={styles.img}src="/images/blackhole.png" width={1200} height={800}/>
          </div>
          <div id="game" className={styles.game}>
            <h2 className={styles.gameHeader}>GAME OVERVIEW</h2>
           <div className={styles.container}>
            <div className={styles.basics}>
              <p className={styles.basTxt}>Learn the Basics</p>
            <Image className={styles.sun} src="/images/sun1.png" width={395} height={385}/>
            </div>
            <div className={styles.rightCol}>
              <div className={styles.mini}>
              <p className={styles.miniTxt}>Mini Games</p>
            <Image className={styles.card} src="/images/card1.png" width={200} height={200}/>
                </div>
              <div className={styles.plan}>
              <p className={styles.planTxt}>Game Plan</p>
            <Image className={styles.load} src="/images/plan.png" width={170} height={170}/>
                </div>
            </div>
           </div>
        </div>
        <div id="charac" className={styles.characters}>
          <h2 className={styles.gameHeader}>MEET THE CHARACTERS</h2>
          <div className={styles.caro}>
          <Carousel/>
          </div>
        </div>
        <div className={styles.comp}>
          <h2 className={styles.gameHeader}>COMPANIONS</h2>
         <div className={styles.alicar}> <AlienCar/>
         </div>
        </div>


        <div  id="about" className={styles.about}>
        <h2 className={styles.gameHeader}>ABOUT US</h2>
        <div className={styles.content}>
        <h3>MD3 Design Team</h3>
        <p>Meet the design team! Each member has had a hand in creating the game assets, prototypes, music, and testing to make sure it is ready for the world! </p>
        <div className={styles.md3}>
        <h4>Anika</h4>
        <h4>Ivona</h4>
        <h4>Kyle</h4>
        <h4>Jacob</h4>
        </div>
        
        <h3>FSWD Development Team</h3>
        <p>Meet the development team! Each memeber has had a hand in bringing all the assets together to create a well produced high functioning game for you and the world to take part of!</p>
        <div className={styles.fswd}>
        <h4>Moh</h4>
        <h4>Jamie</h4>
        <h4>Tony</h4>
        <h4>Devynn</h4>
        </div>
        </div>
        </div>
        <div className={styles.high}>
          <h2 className={styles.gameHeader}>HIGHLIGHTS</h2>
          <div className={styles.quotes}>
          <h4 className={styles.quo}>"One of the best online board games around!"</h4>
          <p className={styles.name}>-Nancy BC</p>
          <h4 className={styles.quo}>"The mini games keep you on the edge of your seats!"</h4>
          <p className={styles.name}>-Jayden ON </p>
          <h4 className={styles.quo}>"The theme is a really cool concept!"</h4>
          <p className={styles.name}>-Lilly AB</p>
          </div>
        </div>
        <FooterBar/>
      </main>
    </>
  )
}
