import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Nav from '@/components/NavBar'

export default function Home() {
  return (
    <>
      <Head>
        <title>LightSpeed
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className={styles.main}>
      <Nav/>
      <div id="home">
    <h1 className={styles.header}>Light Speed</h1>
      </div>
      <div id="Play Now">
        <h2>Play Now </h2>
        </div>
        <div>
          <div id="link1">
        <h2>Learn the basics </h2>
          </div>
          <div id="link2">
            <h2>Understand the mini games</h2>
          </div>
          <div id="link3">
            <h2>Game Plan</h2>
          </div>
        
        </div>
      </main>
    </>
  )
}
